Use with **jp2_data_load** kernel

References:  
https://stackoverflow.com/questions/26681756/how-to-convert-a-python-numpy-array-to-an-rgb-image-with-opencv-2-4

In [1]:
import glymur
import os
import glob
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import pandas as pd

In [3]:
data=os.path.join(os.getcwd()+"/data")
seq_3=os.path.join(data+'/*1003.jp2')
print(seq_3)
#print(glob.glob(seq_3+"/*.jp2")[0:100])
files=glob.glob(seq_3+"/*.jp2")[500:501]
files

/mnt/batch/tasks/shared/LS_root/mounts/clusters/sn-lab-d13/code/users/supanaesw/Seismic_noise_segmentation/data/*1003.jp2


['/mnt/batch/tasks/shared/LS_root/mounts/clusters/sn-lab-d13/code/users/supanaesw/Seismic_noise_segmentation/data/STP10-D1774P1003.jp2/00001022.10.jp2']

In [6]:
save_location=glob.glob(os.path.join(data+'/*1003.npy'))[0]
for f in files:
    fjp2=glymur.Jp2k(f)
    fname=f.split("/")[-1].split(".")[:2]
    p=""+fname[0]+"."+fname[1]+"_int8.npy"
    
    nmp_f=fjp2[:]
    nmp_f=nmp_f.T
    print(nmp_f.dtype)
#     nf_name=save_location+"/"+p
#     print("saving "+f.split("/")[-1]+" to "+p)
#     nmp_f.dump(nf_name)


# plt.imshow(nmp_f.T,cmap="Greys",aspect="auto")
# plt.tight_layout()
# plt.show()

# plt.imshow(data.T,cmap="Greys",aspect="auto")
# plt.tight_layout()
# plt.show()

uint16


In [26]:
info

iinfo(min=0, max=65535, dtype=uint16)

In [27]:
data

array([[50176, 49280, 48384, ..., 26112, 26624, 27136],
       [43328, 42992, 42656, ..., 25568, 25952, 26336],
       [36480, 36704, 36928, ..., 28096, 28352, 28608],
       ...,
       [33152, 33152, 33152, ..., 31872, 31872, 31872],
       [32384, 32384, 32384, ..., 28928, 28928, 28928],
       [32384, 32384, 32384, ..., 32000, 32000, 32000]], dtype=uint16)

In [30]:
data_norm=data.astype(np.float64)/info.max

In [32]:
data_scaled=data_norm*255
data_scaled

array([[195.23735409, 191.75097276, 188.26459144, ..., 101.60311284,
        103.59533074, 105.58754864],
       [168.59143969, 167.28404669, 165.9766537 , ...,  99.48638132,
        100.98054475, 102.47470817],
       [141.94552529, 142.81712062, 143.68871595, ..., 109.3229572 ,
        110.31906615, 111.3151751 ],
       ...,
       [128.99610895, 128.99610895, 128.99610895, ..., 124.0155642 ,
        124.0155642 , 124.0155642 ],
       [126.0077821 , 126.0077821 , 126.0077821 , ..., 112.56031128,
        112.56031128, 112.56031128],
       [126.0077821 , 126.0077821 , 126.0077821 , ..., 124.51361868,
        124.51361868, 124.51361868]])

In [34]:
data_uint8=data_scaled.astype(np.uint8)
data_uint8

array([[195, 191, 188, ..., 101, 103, 105],
       [168, 167, 165, ...,  99, 100, 102],
       [141, 142, 143, ..., 109, 110, 111],
       ...,
       [128, 128, 128, ..., 124, 124, 124],
       [126, 126, 126, ..., 112, 112, 112],
       [126, 126, 126, ..., 124, 124, 124]], dtype=uint8)

In [10]:
data=data.astype(np.float64)/info.max 
print(data)
data=data*255
print()
print(data)


[[0.76563668 0.7519646  0.73829252 ... 0.39844358 0.4062562  0.41406882]
 [0.6611429  0.65601587 0.65088884 ... 0.39014267 0.39600214 0.4018616 ]
 [0.55664912 0.56006714 0.56348516 ... 0.42871748 0.43262379 0.4365301 ]
 ...
 [0.50586709 0.50586709 0.50586709 ... 0.48633555 0.48633555 0.48633555]
 [0.49414817 0.49414817 0.49414817 ... 0.44141299 0.44141299 0.44141299]
 [0.49414817 0.49414817 0.49414817 ... 0.4882887  0.4882887  0.4882887 ]]

[[195.23735409 191.75097276 188.26459144 ... 101.60311284 103.59533074
  105.58754864]
 [168.59143969 167.28404669 165.9766537  ...  99.48638132 100.98054475
  102.47470817]
 [141.94552529 142.81712062 143.68871595 ... 109.3229572  110.31906615
  111.3151751 ]
 ...
 [128.99610895 128.99610895 128.99610895 ... 124.0155642  124.0155642
  124.0155642 ]
 [126.0077821  126.0077821  126.0077821  ... 112.56031128 112.56031128
  112.56031128]
 [126.0077821  126.0077821  126.0077821  ... 124.51361868 124.51361868
  124.51361868]]


In [11]:
img=data.astype(np.uint16)

In [17]:

img.dump(os.getcwd()+"/uint16.npy")

In [25]:
fjp2=glymur.Jp2k(files[0])
data=fjp2[:]
info=np.iinfo(data.dtype)

In [39]:
uint8_path=os.getcwd()+"/shot_uint8.npy"
uint16_path=os.getcwd()+"/shot_uint16.npy"
float64_path=os.getcwd()+"/shot_float64.npy"

orig,norm,scaled,formated=save_in_format(data,np.uint8,uint8_path)

combined=np.array([orig.reshape(-1),norm.reshape(-1),scaled.reshape(-1),formated.reshape(-1)])

combined=combined.T
combined.shape

df=pd.DataFrame(combined,columns=["orig","norm","scaled","formated"])
df.hist()