In [1]:
import obspy
import os
import glob
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from plotly.offline import init_notebook_mode,iplot
from plotly.graph_objs import *

init_notebook_mode(connected=True)

In [18]:
def save_in_format(np_ar,format_type,path):
    info=None
    if np_ar.dtype==np.float64:
        info=np.finfo(np_ar.dtype)
    else:
        info=np.iinfo(np_ar.dtype)
    np_ar_norm=np_ar.astype(np.float64)/info.max 
    print(np_ar_norm)
    np_ar_scaled=np_ar_norm*255
    print()
    print(np_ar_scaled)
    np_ar_format=np_ar_scaled.astype(format_type)
    np_ar_format.dump(path)
    return np_ar,np_ar_norm,np_ar_scaled,np_ar_format
    
    

In [10]:
gdata=np.load(os.getcwd()+"/gain_data_f64.npy",allow_pickle=True)

In [24]:
gdata.astype(np.uint16)

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     0,     0, ...,     0,     0,     0],
       [    0,     0,     0, ...,     0,     0,     0],
       ..., 
       [41751, 51379, 27477, ...,  2693, 42012, 43836],
       [40245, 37112, 63607, ...,  2710, 41381, 43295],
       [38785, 22882, 34227, ...,  2727, 40750, 42754]], dtype=uint16)

In [13]:
np.finfo(gdata.dtype)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [19]:
path=os.getcwd()+"/gain_data_uint16.npy"
save_in_format(gdata,np.uint16,path)

[[  0.00000000e+000   0.00000000e+000   0.00000000e+000 ...,
    0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  6.68749018e-310   4.60325562e-310   3.59653994e-310 ...,
    3.60078433e-310   3.44209815e-310   3.49605759e-310]
 [  2.58303068e-309   1.79519334e-309   1.44196702e-309 ...,
    1.42706917e-309   1.36343123e-309   1.38555856e-309]
 ..., 
 [  1.69047632e-303   6.50363747e-304  -5.76267124e-304 ...,
   -7.14134484e-304  -4.95414122e-304  -4.85267277e-304]
 [  2.04665428e-303   9.35558196e-304  -3.75287988e-304 ...,
   -7.14039784e-304  -4.98924691e-304  -4.88277969e-304]
 [  2.40308630e-303   1.22095624e-303  -1.74165139e-304 ...,
   -7.13944852e-304  -5.02437654e-304  -4.91290702e-304]]

[[  0.00000000e+000   0.00000000e+000   0.00000000e+000 ...,
    0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  1.70531000e-307   1.17383018e-307   9.17117684e-308 ...,
    9.18200004e-308   8.77735028e-308   8.91494686e-308]
 [  6.58672824e-307   4.57774303e-307   3.67701

(array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  1.20220552e-01,   8.27524102e-02,   6.46547516e-02, ...,
           6.47310527e-02,   6.18783621e-02,   6.28483873e-02],
        [  4.64349653e-01,   3.22720675e-01,   2.59221422e-01, ...,
           2.56543246e-01,   2.45103097e-01,   2.49080912e-01],
        ..., 
        [  3.03895768e+05,   1.16915444e+05,  -1.03595145e+05, ...,
          -1.28379466e+05,  -8.90602566e+04,  -8.72361652e+04],
        [  3.67925635e+05,   1.68184655e+05,  -6.74652640e+04, ...,
          -1.28362442e+05,  -8.96913491e+04,  -8.77773954e+04],
        [  4.32001175e+05,   2.19490466e+05,  -3.13095474e+04, ...,
          -1.28345376e+05,  -9.03228722e+04,  -8.83189922e+04]]),
 array([[  0.00000000e+000,   0.00000000e+000,   0.00000000e+000, ...,
           0.00000000e+000,   0.00000000e+000,   0.00000000e+000],
        [  6.68749018e-310,   4.60325562e-310,   3.596

In [20]:
g_uint16=np.load(path,allow_pickle=True)

In [23]:
g_uint16==0

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ..., 
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]], dtype=bool)

In [329]:

trace0 = Scatter(
  x=[1, 2, 3, 4],
  y=[10, 15, 13, 17]
)
trace1 = Scatter(
  x=[1, 2, 3, 4],
  y=[16, 5, 11, 9]
)
data = Data([trace0, trace1])

(data)  

NameError: name 'plot' is not defined

In [25]:
import plotly.express as px
import numpy as np
img_rgb = gdata.astype(np.uint8)
fig = px.imshow(img_rgb)
fig.show()

In [5]:
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Bar(x=[1, 2, 3], y=[1, 3, 2]))

fig.show()