In [4]:
import xarray as xr
import numpy as np

In [15]:
ds=xr.Dataset(
    {   "amplitudes":(("shots","chans","time"),np.random.rand(3,6,3)) },
    coords={
            "chans":[10,20,30,40,50,60],
            "time":[42,43,44],
            "offset":("chans",list("nnmmff")),       #x=10 and x=20 are nears, 30,40 are mids, 50,60 are fars
            "shots":[0,1,2]
        
    },
    attrs={
        "chans":"number of channels",
        "shots":"shot range",
        "time" :"number of time samples"
    }
)
ds

<xarray.Dataset>
Dimensions:     (chans: 6, shots: 3, time: 3)
Coordinates:
  * chans       (chans) int64 10 20 30 40 50 60
  * time        (time) int64 42 43 44
    offset      (chans) <U1 'n' 'n' 'm' 'm' 'f' 'f'
  * shots       (shots) int64 0 1 2
Data variables:
    amplitudes  (shots, chans, time) float64 0.4148 0.4661 ... 0.7631 0.3953
Attributes:
    chans:    number of channels
    shots:    shot range
    time:     number of time samples

**Shot Domain**  
Selecting a single shot

In [25]:
ds.sel(shots=1).amplitudes.shape

(6, 3)

**Channel Domain**

In [24]:
ds.sel(chans=[20,30]).amplitudes.shape

(3, 2, 3)

**Time slices**  
Non-cube**

In [26]:
ds.sel(time=42).amplitudes.shape

(3, 6)

**Group by** the offsets 

In [12]:
ds.groupby('offset').groups

{'f': [4, 5], 'm': [2, 3], 'n': [0, 1]}

**Aggregation**  
What does the average shot look like? i.e average along the shot direction. i.e. across all shots

In [29]:
ds.amplitudes.mean(dim="shots")

<xarray.DataArray 'amplitudes' (chans: 6, time: 3)>
array([[0.59282098, 0.42725718, 0.37664156],
       [0.49017935, 0.55139796, 0.23312327],
       [0.52694597, 0.36770068, 0.42016772],
       [0.66094671, 0.57513393, 0.63093329],
       [0.60545885, 0.28643223, 0.66524745],
       [0.50483049, 0.5850021 , 0.41131325]])
Coordinates:
  * chans    (chans) int64 10 20 30 40 50 60
  * time     (time) int64 42 43 44
    offset   (chans) <U1 'n' 'n' 'm' 'm' 'f' 'f'

In [46]:
ds.amplitudes.mean(dim="chans")

# For a single shot, single time, take all channels and average them,
# s=0
# for i in range(0,6):
#     s+=ds.amplitudes[0,i,0]
# s=s/6
# s


<xarray.DataArray 'amplitudes' (shots: 3, time: 3)>
array([[0.62360238, 0.50713839, 0.40172744],
       [0.67956928, 0.23663426, 0.38579668],
       [0.38741951, 0.65268939, 0.58118915]])
Coordinates:
  * time     (time) int64 42 43 44
  * shots    (shots) int64 0 1 2

In [42]:
ds.amplitudes

<xarray.DataArray 'amplitudes' (shots: 3, chans: 6, time: 3)>
array([[[4.14781547e-01, 4.66062227e-01, 1.74839781e-01],
        [5.98217707e-01, 2.13911471e-01, 7.42442651e-05],
        [7.04979955e-01, 7.25423437e-02, 5.12416733e-01],
        [6.99945962e-01, 7.74814498e-01, 7.43168235e-01],
        [4.28974588e-01, 5.62810506e-01, 7.91599217e-01],
        [8.94714526e-01, 9.52689316e-01, 1.88266437e-01]],

       [[8.63756081e-01, 7.29902906e-02, 7.22525857e-01],
        [8.61090452e-01, 6.82548002e-01, 1.82863306e-01],
        [6.89177549e-01, 3.32203372e-01, 1.42011985e-01],
        [8.58625128e-01, 1.51668684e-01, 2.19548698e-01],
        [5.19825675e-01, 1.41218026e-01, 3.97426083e-01],
        [2.84940785e-01, 3.91771781e-02, 6.50404127e-01]],

       [[4.99925314e-01, 7.42719025e-01, 2.32559041e-01],
        [1.12298859e-02, 7.57734413e-01, 5.16432257e-01],
        [1.86680396e-01, 6.98356337e-01, 6.06074440e-01],
        [4.24269027e-01, 7.98918602e-01, 9.30082931e-01],
        [8.67576291e-01, 1.55268167e-01, 8.06717043e-01],
        [3.34836167e-01, 7.63139808e-01, 3.95269172e-01]]])
Coordinates:
  * chans    (chans) int64 10 20 30 40 50 60
  * time     (time) int64 42 43 44
    offset   (chans) <U1 'n' 'n' 'm' 'm' 'f' 'f'
  * shots    (shots) int64 0 1 2

<xarray.DataArray 'amplitudes' ()>
array(0.62360238)
Coordinates:
    chans    int64 10
    time     int64 42
    offset   <U1 'n'
    shots    int64 0